---
title: "Working with Spatial Data in R"
author: "Chirar, Layla"
editor: visual
---

## Data

Alaska ragional boundaries, community locationsa nd population, and Alaska rivers data will be used, obtained from https://dev.nceas.ucsb.edu/view/urn:uuid:6f07cb25-a4a1-48e8-95cb-74f532f3ce2d

## Analysis

```{r}

library(readr)
library(here)
library(sf)
library(ggplot2)
library(leaflet)
library(scales)
library(ggspatial)
library(dplyr)

```

```{r}
# read in shapefile using read_sf()
ak_rgns_sf <- read_sf(here("data/ak_regions_simp.shp"))
```

```{r}
# quick plot
plot(ak_rgns_sf)
```

```{r}
glimpse(ak_rgns_sf)
```

```{r}
#viewing the coordinate reference system
st_crs(ak_rgns_sf)
```

```{r}
#transofrming the crs to the Alaska ALbers projection
ak_rgns_3338_sf <- ak_rgns_sf %>%
    st_transform(crs = 3338)
```

```{r}
#viewing the new coordinate reference system
st_crs(ak_rgns_3338_sf)
```

```{r}
#plotting using new crs
plot(ak_rgns_3338_sf)
```

```{r}
# returns the names of all the columns in dataset
colnames(ak_rgns_3338_sf)
```

```{r}
ak_rgns_3338_sf %>%
    select(region)
```

```{r}
#checks all variables
unique(ak_rgns_3338_sf$region)
```

```{r}
#filters for southeast region
ak_rgns_3338_sf %>%
    filter(region == "Southeast")
```

```{r}
# read in population data
pop_df <- read_csv(here("data/alaska_population.csv"))
```

```{r}
#turning pop into spatial object
pop_4326_sf <- st_as_sf(pop_df,
                        coords = c('lng', 'lat'),
                        crs = 4326,
                        remove = F)

```

```{r}
head(pop_4326_sf)
```
